### PR TITLE
aio app add/delete service

### PR DESCRIPTION
**Pull request by moritzraho**
## Description

- [x]  Needs to bump @adobe/generator-aio-console once changes in adobe/generator-aio-console#11 are released
- [x] to be merged after #354

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by moritzraho** [comment]
Note tests are failing in gh-actions for now because adobe/generator-aio-console#11 is not merged and released yet. On local machine with `npm link`ing tests are done

**Comment by moritzraho** [comment]
> Note tests are failing in gh-actions for now because adobe/generator-aio-console#11 is not merged and released yet. On local machine with npm linking tests are done

Turned out to be trickier than this, all `TheCommand.run()` in jest tests require all the commands, which in turns requires `generator-aio-console/lib/console-cli.js` from the new add service commands. Which does some operations on inquirer, however inquirer is mocked in jest.setup and needs to bee mocked in `app use` tests, which make the require fail.
Fixed this in the console generator, by delaying the prompt setup in an init method

**Comment by moritzraho** [comment]
ready to review :)

**Comment by shazron** [comment]
I have an issue, see the log:
```
❯ aio console ws select 4566206088344598433
Retrieving the Workspace with id: 4566206088344598433... done
Workspace selected Stage
You are currently in:
1. Org: Adobe IO DEMO
2. Project: ShazFF8
3. Workspace: Stage
❯ aio app add service
Workspace MyWorkspace is currently subscribed to the following services:
[
  "Lightroom / Camera Raw API",
  "Adobe Analytics"
]
? Add Services to the Workspace MyWorkspace? Clone Services from another Workspace in the same Project
? Select Workspace:
❯ Production
  Stage
```

How does `aio app add service` determine which workspace I am in? After I selected a new workspace via `aio console ws select`, it still used the previous workspace.

**Comment by moritzraho** [comment]
Hi @shazron, `aio console ws select` is writing to the global config file. And `app plugin` is using `.aio`.

> Edit: I see that the workspace is via .aio. How do we change the workspace?

The old way is to select globally and `aio app use`. But https://github.com/adobe/aio-cli-plugin-app/pull/368 exposes an easier `aio app use -w <wskname>`

**Comment by moritzraho** [comment]
closing in favor of #368

**Pull request closed without merging**
