### PR TITLE
fix: ACNA-1807 - remove deprecated flags in the commands

### PR DESCRIPTION
**Pull request by shazron**
There have been deprecated flags in the app plugin. e.g. `--skip-???` that already have other flag equivalents. 
Removal of these flags is a `breaking change`, thus a `major version bump` to v10.

For the `app deploy` command I didn't change `skip-deploy` to `deploy` with `allowNo:true` because it didn't make sense at all, and removed any tests for `skip-deploy`.

## How Has This Been Tested?

manual testing of app:
- deploy 
- undeploy
- build
-  run

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by sandeep-paliwal** [comment]
@shazron we use one of the skip flags in our Github action( see [https://github.com/adobe/aio-apps-action/blob/master/index.js#L29](https://github.com/adobe/aio-apps-action/blob/master/index.js#L29) ). We should update that code as well to use alternatives and have those actions published and referred to in CI/CD templates. Maybe needs to be tracked as separate issue.

**Comment by shazron** [comment]
> @shazron we use one of the skip flags in our Github action( see https://github.com/adobe/aio-apps-action/blob/master/index.js#L29 ). We should update that code as well to use alternatives and have those actions published and referred to in CI/CD templates. Maybe needs to be tracked as separate issue.

Thanks Sandeep, changing it is easy enough in the action and generator-aio-app add-ci generator. I can add those PRs.
However I saw https://github.com/marketplace/actions/aio-apps is v1 while https://github.com/adobe/aio-apps-action is v2.0.1 - is there a reason v2 is not published to the marketplace

**Review by purplecabbage — APPROVED** [review]
lgtm!
removing these is not a breaking change, deprecating them was ...

**Comment by shazron** [comment]
@sandeep-paliwal I filed:
1. https://github.com/adobe/aio-apps-action/pull/15 (for a newer 2.0.2 release, see next PR)
2. https://github.com/adobe/generator-aio-app/pull/202

**Pull request merged**
