### PR TITLE
ACNA-976 - feat: add new app event hooks for custom build scripts

### LINKED ISSUE #339: feat: add new app event hooks for custom build scripts
The current event hooks are defined at https://www.adobe.io/apis/experienceplatform/project-firefly/docs.html#!AdobeDocs/project-firefly/master/guides/app-hooks.md

These are the current list of 6 hooks. Note that they do not apply to all commands, only some (for example, deploy hooks don't apply to `aio app run`):
```
1. pre-app-run
2. pre-app-build
3. post-app-build
4. pre-app-deploy
5. post-app-deploy
6. post-app-run
```

The new list would contain 4 new hooks, and would apply to all applicable commands:
```
1. pre-app-run
2. pre-app-build
3. build-actions (replaces default tooling if present)
4. build-static (replaces default tooling if present)
5. post-app-build
6. pre-app-deploy
7. deploy-actions (replaces default tooling if present)
8. deploy-static (replaces default tooling if present)
9. post-app-deploy
10. post-app-run
```

The motivation here is that there are some apps that need to customize how the static files are being built (custom webpack for example), and they also might need to customize how the actions are being built (package static files with the action, for example)

### PR DESCRIPTION
**Pull request by shazron**
Fixes #339 

## How Has This Been Tested?

- npm test
- add `build-actions` and/or `build-static` run scripts in `package.json` for your app, run `aio app build`
- add `deploy-actions` and/or `deploy-static` run scripts in `package.json` for your app, run `aio app deploy`

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by purplecabbage** [comment]
Lgtm!
Why the long timeout?

**Comment by Himavanth** [comment]
LGTM. Just two minor comments.
- Jesse's comment on timeout
- Should we make `skip-static` and `skip-actions` mutually exclusive just like `skip-deploy` and `skip-build` ? (would be a breaking change in another PR anyway)

**Review by Himavanth — APPROVED** [review]

**Comment by shazron** [comment]
> Lgtm!
> Why the long timeout?

ah, no need for the timeout actually after my tests. I thought some tests were failing because of timeout.

**Comment by shazron** [comment]
> Should we make skip-static and skip-actions mutually exclusive
I agree. Like you mentioned this would be a breaking change so let's do it in another PR.
The only remote use-case I can see why someone would want to use both flags is if they want the `pre` and `post` hooks to run for some reason.

**Pull request merged**
