### PR TITLE
fix: ACNA-1687 | fix option skipInstall for generators

### PR DESCRIPTION
**Pull request by arjuncooliitr**
Fixed option `skipInstall` for yeoman generators used for scaffolding App Builder Apps

## Description
This PR aims to fix skipInstall options issue with yeoman generators. There is a slight change to how to use this option to make it work.

## Related Issue
https://github.com/adobe/aio-cli-plugin-app/issues/554

## Motivation and Context
npm dependencies seem to be installed twice once after the base-app gets generated and at the end before the app initialization is over
Expected behaviour: npm dependencies should only be installed at the end of the project initialization once the package.json deps are all defined.

## How Has This Been Tested?
Locally tested by creating an app - npm packages are now installed only at the end. Generators skip installing packages. All units tests run successful locally.

## Screenshots (if appropriate):
Generators skipping installing packages: 
image

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by moritzraho — APPROVED** [review]
LGTM, looks like you had to do the same changes more times than I can count 😄

**Comment by purplecabbage** [comment]
This looks good.
Please remove the repeated commented out line:
```
// Moving ['skip-install': true] to env.options due to yeoman environment issue https://github.com/yeoman/environment/issues/421
```
We can use git blame or other means to go back in time ... no need to maintain historical code in the comments.

**Review by purplecabbage — APPROVED** [review]
Just the comment about removing the commented code ... looks good!

**Comment by arjuncooliitr** [comment]
Hi @purplecabbage, Thanks for reviewing. I have removed the historic code comment. Can I merge this PR now?

**Review by sandeep-paliwal — APPROVED** [review]

**Pull request merged**
