### PR TITLE
fix: ACNA-1741 - invalid config error

### PR DESCRIPTION
**Pull request by amulyakashyap09**
## Description

- `aio-cli` throws error of invalid credentials when validated against config schema
- When api mesh service is added, it has a type of authorisation mechanism which only needs apikey (client id) NO client_secret key is required
- At backend it throws error as it requires client_secret too

## Related Issue

[ACNA-1741](https://jira.corp.adobe.com/browse/ACNA-1741)

## Motivation and Context

This is one of critical issues as it does not generate a app builder project

## How Has This Been Tested?

- Test case fixtures has been added for `valid.config.json` and `100%` passing
- Test case fixtures has been added for `invalid.config.json` and `100%` passing
- Tested with Local repo linking between `aio-cli-plugin-app` and `aio-cli`
- App builder project is generating without any error.

## Screenshots (if appropriate):
Screenshot 2022-08-19 at 1 10 55 PM

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by sandeep-paliwal** [comment]
@amulyakashyap09 Changes look good. 
We will also need to add tests which validate API Mesh schema changes. Possibly a new test config in fixtures.

**Comment by amulyakashyap09** [comment]
> 

Done

**Review by sandeep-paliwal — APPROVED** [review]
LGTM

**Review by MichaelGoberling — APPROVED** [review]
LGTM!

**Review by shazron — APPROVED** [review]

**Pull request merged**
