### PR TITLE
update major for aio-cli-lib-app-config

### PR DESCRIPTION
**Pull request by moritzraho**
## Description

*TO DISCUSS: potential breaking  change because now every command that loads the configuration will undergo schema validation (via load in aio-cli-lib-app-config) and we may have some corner cases that were working without being valid*

Depends on a release for https://github.com/adobe/aio-cli-lib-app-config/pull/21 and https://github.com/adobe/aio-cli-lib-app-config/pull/22

- async config
- no validation here, use aio-cli-lib-app-config instead.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by moritzraho** [comment]
Note tests are failing here but passing with local linking of  aio-cli-lib-app-config

**Review by shazron — APPROVED** [review]
LGTM for code review - I haven't had a chance to test it by running the command yet, will do so next week

**Comment by moritzraho** [comment]
do not merge yet.
pre-release at `@adobe/aio-cli-plugin-app@next`
needs release of aio-cli-lib-app-config and updated package.json

**Comment by moritzraho** [comment]
closing this for now as it is outdated

**Comment by moritzraho** [comment]
For now let's just disable validation to move forward, see https://github.com/adobe/aio-cli-lib-app-config/pull/32

**Pull request closed without merging**
