### PR TITLE
fix: increase jest timeout to 30s from 15s

### PR DESCRIPTION
**Pull request by shazron**
This is to fix timeout issues under node-14 for the Github Action daily.yml
See https://github.com/adobe/aio-cli-plugin-app/actions/runs/6857278020

## How Has This Been Tested?

This PR is the test.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by shazron** [comment]
At 30s, ubuntu node-14 builds now don't timeout, but now windows node-14 builds time out. 
Increasing timeout to 45s.

**Comment by shazron** [comment]
Now Ubuntu node-14 is failing also when its passing before. Not sure what's going on. I have a suspicion it's an infra issue.

**Comment by shazron** [comment]
Might not be relevant anymore once we merge #745

**Review by MichaelGoberling — APPROVED** [review]

**Review by purplecabbage — APPROVED** [review]
Ideally we find a way to do this without lengthy timeouts, but this find for preventing false alarms until we do.

**Pull request merged**
