### PR TITLE
feat: ACNA-1650 - Template Registry Api integration

### PR DESCRIPTION
**Pull request by shazron**
## Description

This connects with the Template Registry API so we can bootstrap App Builder apps with pre-defined templates available in the registry, and not with pre-packaged templates.

Note: this has been tested with the pre-release cli at `@adobe/aio-cli-next` (`aio-next` executable)
### Features changed:

- aio app init
  - be aware of this multiple flag oclif bug if you use `--template` or `--extension`. The appname argument must be before those flags: https://github.com/oclif/core/issues/496 
- aio app add extension
- aio app add action
  - right now there is a generic filtering of categories: we need to refine the categories for this search  
- aio app add web-assets
  - right now there is a generic filtering of categories: we need to refine the categories for this search  
- aio app delete extension

## How Has This Been Tested?

- aio plugins link .
- aio plugins install @adobe/aio-cli-plugin-app-templates
- aio app init --help (to see options)
- aio app add extension --help
- aio app add web-assets --help
- aio app delete extension --help

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Review by purplecabbage — APPROVED** [review]
This looks good, _but_ there is a lot here!
I only looked through the code, I did not run it, try it, test it.

**Comment by shazron** [comment]
> This looks good, _but_ there is a lot here! I only looked through the code, I did not run it, try it, test it.

The pre-release will get this out in more hands to test. Will merge and get this out.

**Comment by shazron** [comment]
Open sourced: https://www.npmjs.com/package/@adobe/inquirer-table-checkbox and tested, so I will update the reference in package.json and code

**Comment by shazron** [comment]
Note: we still have this special-case for the `dx/excshell/1 extension` that could not be resolved: https://github.com/adobe/aio-cli-plugin-app/blob/35dd448c5a12f7a189a0243467f2db38c0d483dc/src/commands/app/deploy.js#L250-L253
It is expected that cli plugin hooks (upcoming feature) will help with this.

**Pull request merged**
