### PR TITLE
display action urls on deployment & run

### LINKED ISSUE #91: show action urls in run and deploy output
## current
- no easy way of knowing action urls, especially annoying in backend only projects

## good to have
- display urls for deploy and run cmd

### PR DESCRIPTION
**Pull request by moritzraho**
**To be merged after https://github.com/adobe/aio-app-scripts/pull/81**
and after https://github.com/adobe/aio-app-scripts is released

## Description

fixes #91 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by moritzraho** [comment]
@purplecabbage @sandeep-paliwal any of you for review?

**Comment by moritzraho** [comment]
> LGTM

Thanks ! When you get the chance (no rush) could you also review adobe/aio-app-scripts#81 ?

**Comment by OmarEltobgy** [comment]
@moritzraho Can you please tell me when this PR is expected to be merged ? 
We have been waiting for it so that we can use it in our CI/CD pipeline.

**Comment by moritzraho** [comment]
@OmarEltobgy merged, will release a new version in a bit

**Pull request merged**
