### PR TITLE
Support having actions at any folder level

### PR DESCRIPTION
**Pull request by tmathern**
Check for manifest presence.

Check for manifest presence to support having deployable actions at any folder level.

https://github.com/adobe/aio-cli-plugin-app/issues/168
Also, NUI-246.

## Motivation and Context

Nui needs this to deploy.

## How Has This Been Tested?

Updated unit tests.

## Types of changes

- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ x] I have read the **CONTRIBUTING** document.
- [ x] I have added tests to cover my changes.
- [ x] All new and existing tests passed.

### CODE REVIEW

**Comment by moritzraho** [comment]
Hi @tmathern,

would it be ok for you to change the condition from has actions/ folder to has ./manifest.yml file.

@sandeep-paliwal  is currently implementing the UI only case and checks backend existance by checking the manifest.yml file see https://github.com/adobe/aio-app-scripts/pull/80/files#diff-59e86d77d535d34e7d6039470196fc03R118

**Comment by alexkli** [comment]
@moritzraho Makes sense.

**Comment by tmathern** [comment]
@moritzraho Ack. I updated the PR to rely on manifest.yml for deployment.

**Comment by moritzraho** [comment]
thanks @tmathern! merging the PR

**Pull request merged**
