### PR TITLE
fix: update openwhisk standalone config for new node-20 runtime and tags

### PR DESCRIPTION
**Pull request by shazron**
## How Has This Been Tested?

- aio app run --local should download the appropriate image in Docker

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by MichaelGoberling** [comment]
Looks like last time this was completed by Jesse ([commit](https://github.com/adobe/aio-cli-plugin-app/commit/a2ead91997d0881f483b1d8461d0fa417ea63c49)), the default kind was updated to the latest

Should we do that here too or is there a reason we're deferring?

**Review by moritzraho — APPROVED** [review]

**Comment by shazron** [comment]
@MichaelGoberling the default kind when I created this PR was 16 - I verified via `curl https://adobeioruntime.net` and inspecting the json. But with the new runtimes release this week it was updated to 18. I'll revert that line.

**Comment by shazron** [comment]
@MichaelGoberling The default kind is determined by the `default` key in the output of `curl https://adobeioruntime.net` (which runtimes.json is).

**Comment by shazron** [comment]
Sorry I was confused - runtimes.json is just our own version of the curl output. There is no reason it should be tied to the actual runtime server default kind, but maybe it should?

**Review by purplecabbage — COMMENTED** [review]
all good

**Pull request merged**
