### PR TITLE
Enabling hmr for parcel

### PR DESCRIPTION
**Pull request by Himavanth**
## Description
Fixes https://github.com/adobe/aio-cli-plugin-app/issues/410

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by shazron** [comment]
I get this error during `aio  app run` on a fresh project with the react template. But this is even without your PR yet:
```
To view your local application:
  -> https://localhost:9080
To view your deployed application in the Experience Cloud shell:
  -> https://experience.adobe.com/?devMode=true#/custom-apps/?localDevUrl=https://localhost:9080
press CTRL+C to terminate dev environment
 Building react-refresh-runtime.development.js...
The above error occurred in the <UI> component:
    in UI
    in App

React will try to recreate this component tree from scratch using the error boundary you provided, App.
Warning: App: Error boundaries should implement getDerivedStateFromError(). In that method, return a state update to display an error message or fallback UI.
(node:90444) UnhandledPromiseRejectionWarning: Error: Got unexpected null
    at nullthrows (/Users/shazron/Documents/git/adobe/aio-cli-plugin-app/node_modules/nullthrows/nullthrows.js:7:15)
    at PackagedBundle.get filePath [as filePath] (/Users/shazron/Documents/git/adobe/aio-cli-plugin-app/node_modules/@parcel/core/lib/public/Bundle.js:373:38)
    at getProgressMessage (/Users/shazron/Documents/git/adobe/aio-cli-plugin-app/node_modules/@parcel/reporter-cli/lib/utils.js:21:63)
    at reducer (/Users/shazron/Documents/git/adobe/aio-cli-plugin-app/node_modules/@parcel/reporter-cli/lib/UI.js:85:53)
    at /Users/shazron/Documents/git/adobe/aio-cli-plugin-app/node_modules/@parcel/reporter-cli/lib/UI.js:44:68
    at updateReducer (/Users/shazron/Documents/git/adobe/aio-cli-plugin-app/node_modules/react-reconciler/cjs/react-reconciler.development.js:6367:23)
    at Object.useReducer (/Users/shazron/Documents/git/adobe/aio-cli-plugin-app/node_modules/react-reconciler/cjs/react-reconciler.development.js:7122:16)
    at useReducer (/Users/shazron/Documents/git/adobe/aio-cli-plugin-app/node_modules/react/cjs/react.development.js:1501:21)
    at UI (/Users/shazron/Documents/git/adobe/aio-cli-plugin-app/node_modules/@parcel/reporter-cli/lib/UI.js:44:49)
    at renderWithHooks (/Users/shazron/Documents/git/adobe/aio-cli-plugin-app/node_modules/react-reconciler/cjs/react-reconciler.development.js:6036:18)
(node:90444) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:90444) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Review by shazron — APPROVED** [review]
Aside from the (unrelated?) unhandledreject errors reported earlier, HMR looks to be working

**Comment by shazron** [comment]
sorry I did a re-test, those errors show now because of the newly added parcel-reporter. Doesn't seem to affect things, but we should clean it up nonetheless

**Comment by shazron** [comment]
repro steps:
```
mkdir test
cd test
git clone https://github.com/adobe/aio-cli-plugin-app
cd aio-cli-plugin-app
git checkout hmr
npm i
aio plugins link .
# create a new FF project, react template, web-assets, actions
aio app init react-test
cd react-test
aio app run --verbose
```

**Comment by Himavanth** [comment]
thx @shazron . Fixed it.

**Comment by shazron** [comment]
> thx @shazron . Fixed it.

thanks Hima, verified that the warning does not occur anymore and HMR works.

**Pull request merged**
