### PR TITLE
Support console add services on init

### PR DESCRIPTION
**Pull request by moritzraho**
## Description
depends on https://github.com/adobe/generator-aio-console/pull/11

- pass cert-dir to generator

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by moritzraho** [comment]
wdyt about: https://github.com/adobe/aio-cli-plugin-app/pull/354/commits/2faa3639ab34347d31bba2cb6dd423a2279ed687#diff-cad5bea0824717c7247788fa8725f7720a38030642a3a5fd602184dbeafe27c7R63 and https://github.com/adobe/aio-cli-plugin-app/pull/354/commits/2faa3639ab34347d31bba2cb6dd423a2279ed687#diff-cad5bea0824717c7247788fa8725f7720a38030642a3a5fd602184dbeafe27c7R84

which I reverted  to avoid breaking changes, but IMHO it would be better to fail in those cases

**Review by shazron — APPROVED** [review]

**Comment by shazron** [comment]
Tested using:
```
mkdir console-test
cd console-test

git clone https://github.com/adobe/aio-lib-console
cd aio-lib-console
git checkout add-sdkProperties
npm i
cd ..

git clone https://github.com/adobe/generator-aio-console
cd generator-aio-console
git checkout enable-add-services
npm i
npm link ../aio-lib-console
cd ..

git clone https://github.com/adobe/aio-cli-plugin-app
cd aio-cli-plugin-app
git checkout -b moritzraho-support-console-add-services master
git pull https://github.com/moritzraho/aio-cli-plugin-cna.git support-console-add-services
npm i
npm link ../generator-aio-console
aio plugins link .
cd ..


aio app init test-app-1
cd test-app-1
```

I found two issues:
1. I created a new workspace 'Foo'.  Then at some point I got this prompt: `> do you confirm the new Service Subscription list for Workspaces Production and Stage ?`. It should include the newly created workspace in the prompt text.
2. I selected `Target` and `Campaign` for my services to add. Then the section `supported templates for services added to this Adobe Developer Console Workspace` the templates for `Target` and `Campaign` are not listed.
```
? New Service Subscription list:
[
    "Adobe Campaign",
    "Adobe Target"
]
  > do you confirm the new Service Subscription list for Workspaces Production and Stage ? Yes
Key pair 'Production.pem, Production.key' valid for '365' days, has been created into the folder: /Users/shaz/.local/share/@adobe/aio-cli/entp-int-certs/53444-ShazFF4
Key pair 'Stage.pem, Stage.key' valid for '365' days, has been created into the folder: /Users/shaz/.local/share/@adobe/aio-cli/entp-int-certs/53444-ShazFF4
   create console.json

You are about to initialize the project 'ShazFF4'
Generating code in: /Users/shaz/Desktop/tmp/test-app-1
? Which Adobe I/O App features do you want to enable for this project?
Select components to include Actions: Deploy Runtime actions, Web Assets: Deploy hosted static assets


? Which type of sample actions do you want to create?
Select type of actions to generate (Press <space> to select, <a> to toggle all, <i> to invert selecti
on)
 -- supported templates for services added to this Adobe Developer Console Workspace --
❯◉ Generic
 -- templates supported by this Organization, corresponding services should be added to this Workspac
e in https://console.adobe.io/ --
 ◯ Adobe Analytics
 ◯ Adobe Asset Compute Worker
 ◯ Adobe Audience Manager: Customer Data
 ◯ Adobe Campaign Standard
```

**Comment by shazron** [comment]
Note that we don't have a `Adobe Campaign` template, but it should have showed the `Adobe Target` template. I tried again using [`Adobe Analytics`, `Adobe Target`] and the same issue shows up (both templates are available).

**Comment by moritzraho** [comment]
@shazron thanks for the feedback. I fixed 1., still trying to reproduce 2 but somehow I can't see the error.
I used the steps you provided to reproduce as closely as possible your env and tried:
- new project + new workspace
- new project
- new workspace
For all 3 cases I can see the service appearing in the app generator prompt

**Comment by moritzraho** [comment]
could you `Ctrl + C` before the `generator-aio-app` prompts kick in and share the content in `project.workspace.details.services` of `console.json` ?

**Comment by shazron** [comment]
I tried the same repro steps on another computer today and now the services show up 🤷🏼‍♂️

**Comment by moritzraho** [comment]
> I tried the same repro steps on another computer today and now the services show up 🤷🏼‍♂️

now that's odd.. I really could not repro, maybe there was a linking issue on your first machine e.g. an old generator-aio-app? although your steps should ensure clean linking..

Do you feel it's safe to proceed with merging ?

**Pull request merged**
