### PR TITLE
Fix links to source code in README

### PR DESCRIPTION
**Pull request by MichaelGoberling**
Modified README to change file extensions in links to source code from `.ts` to `.js`.

## Motivation and Context

This change is required so that links to source files will work. 

## How Has This Been Tested?

Manually tested via personal fork of repository.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by sandeep-paliwal — APPROVED** [review]
LGTM

**Comment by shazron** [comment]
Actually, the README is generated just before publish, via the npm script in package.json, `prepack` so we shouldn't do manual README changes, it is auto-gen'ed.
The actual error is -- we will have to find out why oclif thinks our source files are typescript, it didn't use to be this way

**Review by shazron — CHANGES_REQUESTED** [review]
Actually, the README is auto-generated by the npm script `prepack` in package.json, right before packing for publishing to npm. (run it via `npm run prepack`).

The actual error we need to investigate is why oclif thinks our source files are Typescript.

**Comment by MichaelGoberling** [comment]
Typescript dependency removed from package.json and confirmed that running `npm run prepack` will generate code links with .js extensions now.

**Pull request merged**
