### PR TITLE
feat: ACNA-1678 - add `--force-build` flag for `aio app run`

### LINKED ISSUE #542: for `aio app run --local` (local deploy), if you ran `aio app run` (remote deploy) beforehand, it won't deploy the action code (and vice versa)
## Expected

Action code is deployed to the local Openwhisk server.

## Actual

Action code is not deployed to the local Openwhisk server, because the CLI thinks there are no changes.

## Investigation

When you ran `aio app run` previously (for remote deploy), it caches a hash of the built actions, and stores the values in `dist/last-built-actions.json`. This hash is checked, so if it is the same, it won't build and won't deploy the action.

However, for `aio app run --local` it is now a local deploy, and you haven't deployed yet (and it won't deploy because the file hashes are the same). So you will get an error during debugging that it can't find the action file.

This also happens vice versa.
## Fix

1. https://github.com/adobe/aio-cli-plugin-app/blob/4c4950f4d6cab65c62be56bd0ed7f3f307d05378/src/lib/build-actions.js#L22 add `skipCheck` as the third parameter, and pass it in as the third parameter here https://github.com/adobe/aio-cli-plugin-app/blob/4c4950f4d6cab65c62be56bd0ed7f3f307d05378/src/lib/build-actions.js#L26
2. https://github.com/adobe/aio-cli-plugin-app/blob/4c4950f4d6cab65c62be56bd0ed7f3f307d05378/src/lib/run-dev.js#L83 (pass in true as the third parameter. the second param set to an empty array)
3. Add a new flag to `aio app run`, like `aio app build`: `--force-build` which will always run the build (skipCheck=true above)

## Workaround

Delete the `dist/last-built-actions.json` file (or run `aio app build` which always forces a build), then run `aio app run --local`

### PR DESCRIPTION
**Pull request by shazron**
## Description

Fixes #542

## How Has This Been Tested?

npm test
manual test

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly (will be auto-gen'ed)
- [X] I have read the **CONTRIBUTING** document.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Review by moritzraho — COMMENTED** [review]
Is there a use case for force build ? can't we just force build transparently on local dev ?
To me force build sounds a bit like we might have some bugs "so just try force build" 😄

**Comment by moritzraho** [comment]
> It's purely for the situation of switching between these two contexts.

Ok maybe we can avoid introducing the new flag by catching this case in code and "force build" transparently to the user instead ?

**Comment by shazron** [comment]
> > It's purely for the situation of switching between these two contexts.
> 
> Ok maybe we can avoid introducing the new flag by catching this case in code and "force build" transparently to the user instead ?

Let me think about it some more. We would have to store the previous state somewhere (remote vs local).

**Comment by shazron** [comment]
Now that I think about it some more, the workaround is just doing a `aio app build` (which always forces the build) before your aio app run if you switch contexts. `aio app build && aio app run --local`

**Comment by shazron** [comment]
You've convinced me. We do an automatic force build on `aio app run` instead.

**Comment by moritzraho** [comment]
hahaha ok ok

**Comment by shazron** [comment]
Closing. Will do another PR for automatic force build on run.

**Pull request closed without merging**
